package com.company.humanResources;

public enum JobTitleEnum {
    NONE, ACCOUNTANT, ADMINISTRATOR, AGENT, ANALYST,
    ASSISTANT, CHIEF_ACCOUNTANT, CHIEF_ENGINEER, DIRECTOR, ENGINEER,
    LEFAL_ADVISER, MANAGER, TECHNICIAN
}
